services:
  django:
    build: 
      context: 
      dockerfile: Dockerfile 
    container_name: noted-django
    environment: 
      - DEBUG=
      - SECRET_KEY=
      - DATABASE_NAME=
      - DATABASE_USER=
      - DATABASE_PASSWORD=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - CACHE_IP=
      - CACHE_PORT=
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
      - YANDEX_CLIENT_ID=
      - YANDEX_SECRET=
      - GITHUB_ID=
      - GITHUB_SECRET=
      - ADMIN_NAME=
      - ADMIN_EMAIL=
    volumes:
      - site:/noted
      - static:/noted/frontend/collected_static
      - avatars:/noted/frontend/media/user
    expose:
      - 8000
    entrypoint: ./entrypoint.sh
    depends_on:
      - db
    networks:
      default:
        ipv4_address: 

  db:
    image: postgres:12
    container_name: noted-db
    environment:
      - POSTGRES_HOST=
      - POSTGRES_USER= 
      - POSTGRES_PORT=
      - POSTGRES_DB= 
      - POSTGRES_PASSWORD=
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432 
    networks:
      default:
        ipv4_address: 

  nginx:
    image: nginx
    container_name: noted-nginx
    volumes:
      - static:/noted/frontend/collected_static
      - avatars:/noted/frontend/media/user
    ports:
      - "8090:8090"
    networks:
      default:
        ipv4_address:   
    depends_on:
      - django

volumes:
  site:
  static:
  avatars:
  postgres_data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 
